{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gitcreds
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gitcreds_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gitcreds/gitcreds_{{ version }}.tar.gz
  sha256: 41c6abcca5635062b123ffb5af2794770eca5ebd97b05c5a64b24fa1c803c75d

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('gitcreds')"           # [not win]
    - "\"%R%\" -e \"library('gitcreds')\""  # [win]

about:
  home: https://github.com/r-lib/gitcreds
  license: MIT
  summary: Query, set, delete credentials from the 'git' credential store. Manage 'GitHub' tokens and other 'git' credentials. This package is to be used by other packages that need to authenticate to 'GitHub' and/or other 'git' repositories.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gitcreds
# Title: Query 'git' Credentials from 'R'
# Version: 0.1.0
# Author: Gabor Csardi
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Query, set, delete credentials from the 'git' credential store. Manage 'GitHub' tokens and other 'git' credentials. This package is to be used by other packages that need to authenticate to 'GitHub' and/or other 'git' repositories.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/gitcreds
# BugReports: https://github.com/r-lib/gitcreds/issues
# RoxygenNote: 7.1.1.9000
# Suggests: testthat, knitr, mockery, oskeyring, rmarkdown, withr
# Encoding: UTF-8
# SystemRequirements: git
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-10-30 14:38:18 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2020-11-06 10:40:02 UTC
